{"totalCount":2,"grade":"C","repositories":[{"url":"https://github.com/MTES-MCT/acceslibre","vulnerabilityAlerts":{"totalCount":2,"nodes":[{"dismissedAt":null,"createdAt":"2022-10-18T18:57:09Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qrw5-5h28-6cmg"},{"type":"CVE","value":"CVE-2022-41323"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-41323"},{"url":"https://github.com/django/django/commit/5b6b257fa7ec37ff27965358800c67e2dd11c924"},{"url":"https://www.djangoproject.com/weblog/2022/oct/04/security-releases/"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-304.yaml"},{"url":"https://github.com/advisories/GHSA-qrw5-5h28-6cmg"}]}}},{"dismissedAt":null,"createdAt":"2022-10-18T19:51:43Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"py"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w596-4wvx-j9j6"},{"type":"CVE","value":"CVE-2022-42969"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-42969"},{"url":"https://github.com/pytest-dev/py/issues/287"},{"url":"https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316"},{"url":"https://pypi.org/project/py"},{"url":"https://github.com/advisories/GHSA-w596-4wvx-j9j6"}]}}}]},"grade":"C"}]}