{"totalCount":29,"grade":"E","repositories":[null,null,{"url":"https://github.com/MTES-MCT/adock-api","vulnerabilityAlerts":{"totalCount":29,"nodes":[{"dismissedAt":null,"createdAt":"2023-07-16T16:20:55Z","securityVulnerability":{"severity":"HIGH","package":{"name":"sqlparse"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-p5w8-wqhj-9hhf"},{"type":"CVE","value":"CVE-2021-32839"}],"references":[{"url":"https://github.com/andialbrecht/sqlparse/security/advisories/GHSA-p5w8-wqhj-9hhf"},{"url":"https://github.com/andialbrecht/sqlparse/commit/8238a9e450ed1524e40cb3a8b0b3c00606903aeb"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-32839"},{"url":"https://securitylab.github.com/advisories/GHSL-2021-107-andialbrecht-sqlparse/"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/sqlparse/PYSEC-2021-333.yaml"},{"url":"https://github.com/advisories/GHSA-p5w8-wqhj-9hhf"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:55Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-v6rh-hp5x-86rv"},{"type":"CVE","value":"CVE-2021-44420"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-44420"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2021/dec/07/security-releases/"},{"url":"https://www.openwall.com/lists/oss-security/2021/12/07/1"},{"url":"https://github.com/django/django/commit/d4dcd5b9dd9e462fec8220e33e3e6c822b7e88a6"},{"url":"https://docs.djangoproject.com/en/3.2/releases/security/"},{"url":"https://security.netapp.com/advisory/ntap-20211229-0006/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/"},{"url":"https://github.com/advisories/GHSA-v6rh-hp5x-86rv"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:55Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jrh2-hc4r-7jwx"},{"type":"CVE","value":"CVE-2021-45452"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-45452"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"},{"url":"https://security.netapp.com/advisory/ntap-20220121-0005/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/"},{"url":"https://github.com/django/django/commit/4cb35b384ceef52123fc66411a73c36a706825e1"},{"url":"https://github.com/django/django/commit/8d2f7cff76200cbd2337b2cf1707e383eb1fb54b"},{"url":"https://github.com/django/django/commit/e1592e0f26302e79856cc7f2218ae848ae19b0f6"},{"url":"https://github.com/advisories/GHSA-jrh2-hc4r-7jwx"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:56Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-53qw-q765-4fww"},{"type":"CVE","value":"CVE-2021-45115"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-45115"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://github.com/django/django/commit/2135637fdd5ce994de110affef9e67dffdf77277"},{"url":"https://github.com/django/django/commit/a8b32fe13bcaed1c0b772fdc53de84abc224fb20"},{"url":"https://github.com/django/django/commit/df79ef03ac867c93caaa6be56bc69e66abfeef8f"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV"},{"url":"https://security.netapp.com/advisory/ntap-20220121-0005"},{"url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases"},{"url":"https://github.com/advisories/GHSA-53qw-q765-4fww"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:56Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8c5j-9r9f-c6w8"},{"type":"CVE","value":"CVE-2021-45116"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-45116"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"},{"url":"https://security.netapp.com/advisory/ntap-20220121-0005/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/"},{"url":"https://github.com/django/django/commit/2a8ec7f546d6d5806e221ec948c5146b55bd7489"},{"url":"https://github.com/django/django/commit/c7fe895bca06daf12cc1670b56eaf72a1ef27a16"},{"url":"https://github.com/django/django/commit/c9f648ccfac5ab90fb2829a66da4f77e68c7f93a"},{"url":"https://github.com/advisories/GHSA-8c5j-9r9f-c6w8"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:56Z","securityVulnerability":{"severity":"HIGH","package":{"name":"ipython"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-pq7m-3gw7-gq5x"},{"type":"CVE","value":"CVE-2022-21699"}],"references":[{"url":"https://github.com/ipython/ipython/security/advisories/GHSA-pq7m-3gw7-gq5x"},{"url":"https://github.com/ipython/ipython/commit/46a51ed69cdf41b4333943d9ceeb945c4ede5668"},{"url":"https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#ipython-8-0-1-cve-2022-21699"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-21699"},{"url":"https://lists.debian.org/debian-lts-announce/2022/01/msg00021.html"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CRQRTWHYXMLDJ572VGVUZMUPEOTPM3KB/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DZ7LVZBB4D7KVSFNEQUBEHFO3JW6D2ZK/"},{"url":"https://github.com/advisories/GHSA-pq7m-3gw7-gq5x"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:56Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-95rw-fx8r-36v6"},{"type":"CVE","value":"CVE-2022-22818"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-22818"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/feb/01/security-releases/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/"},{"url":"https://security.netapp.com/advisory/ntap-20220221-0003/"},{"url":"https://www.debian.org/security/2022/dsa-5254"},{"url":"https://github.com/django/django/commit/01422046065d2b51f8f613409cad2c81b39487e5"},{"url":"https://github.com/django/django/commit/1a1e8278c46418bde24c86a65443b0674bae65e2"},{"url":"https://github.com/django/django/commit/c27a7eb9f40b64990398978152e62b6ff839c2e6"},{"url":"https://github.com/advisories/GHSA-95rw-fx8r-36v6"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:56Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-6cw3-g6wv-c2xv"},{"type":"CVE","value":"CVE-2022-23833"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-23833"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/feb/01/security-releases/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/"},{"url":"https://security.netapp.com/advisory/ntap-20220221-0003/"},{"url":"https://www.debian.org/security/2022/dsa-5254"},{"url":"https://github.com/django/django/commit/c477b761804984c932704554ad35f78a2e230c6a"},{"url":"https://github.com/django/django/commit/d16133568ef9c9b42cb7a08bdf9ff3feec2e5468"},{"url":"https://github.com/advisories/GHSA-6cw3-g6wv-c2xv"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:56Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w24h-v9qh-8gxj"},{"type":"CVE","value":"CVE-2022-28347"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-28347"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/apr/11/security-releases/"},{"url":"http://www.openwall.com/lists/oss-security/2022/04/11/1"},{"url":"https://github.com/django/django/commit/6723a26e59b0b5429a0c5873941e01a2e1bdbb81"},{"url":"https://github.com/advisories/GHSA-w24h-v9qh-8gxj"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-191.yaml"},{"url":"https://www.debian.org/security/2022/dsa-5254"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI/"},{"url":"https://github.com/django/django/commit/00b0fc50e1738c7174c495464a5ef069408a4402"},{"url":"https://github.com/django/django/commit/29a6c98b4c13af82064f993f0acc6e8fafa4d3f5"},{"url":"https://github.com/django/django/commit/9e19accb6e0a00ba77d5a95a91675bf18877c72d"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:56Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-2gwj-7jmv-h26r"},{"type":"CVE","value":"CVE-2022-28346"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-28346"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/apr/11/security-releases/"},{"url":"http://www.openwall.com/lists/oss-security/2022/04/11/1"},{"url":"https://lists.debian.org/debian-lts-announce/2022/04/msg00013.html"},{"url":"https://github.com/django/django/commit/93cae5cb2f9a4ef1514cf1a41f714fef08005200"},{"url":"https://github.com/advisories/GHSA-2gwj-7jmv-h26r"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-190.yaml"},{"url":"https://security.netapp.com/advisory/ntap-20220609-0002/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI/"},{"url":"https://www.debian.org/security/2022/dsa-5254"},{"url":"https://github.com/django/django/commit/2044dac5c6968441be6f534c4139bcf48c5c7e48"},{"url":"https://github.com/django/django/commit/2c09e68ec911919360d5f8502cefc312f9e03c5d"},{"url":"https://github.com/django/django/commit/800828887a0509ad1162d6d407e94d8de7eafc60"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:57Z","securityVulnerability":{"severity":"HIGH","package":{"name":"pyjwt"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-ffqj-6fqr-9h24"},{"type":"CVE","value":"CVE-2022-29217"}],"references":[{"url":"https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-29217"},{"url":"https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc"},{"url":"https://github.com/jpadilla/pyjwt/releases/tag/2.4.0"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO/"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/pyjwt/PYSEC-2022-202.yaml"},{"url":"https://github.com/advisories/GHSA-ffqj-6fqr-9h24"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:57Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-p64x-8rxx-wf6q"},{"type":"CVE","value":"CVE-2022-34265"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-34265"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/jul/04/security-releases/"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-213.yaml"},{"url":"https://github.com/django/django/commit/5e2f4ddf2940704a26a4ac782b851989668d74db"},{"url":"https://github.com/django/django/commit/877c800f255ccaa7abde1fb944de45d1616f5cc9"},{"url":"https://security.netapp.com/advisory/ntap-20220818-0006/"},{"url":"https://github.com/advisories/GHSA-p64x-8rxx-wf6q"},{"url":"https://www.debian.org/security/2022/dsa-5254"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI/"},{"url":"https://github.com/django/django/commit/0dc9c016fadb71a067e5a42be30164e3f96c0492"},{"url":"https://github.com/django/django/commit/a9010fe5555e6086a9d9ae50069579400ef0685e"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:57Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8x94-hmjh-97hq"},{"type":"CVE","value":"CVE-2022-36359"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-36359"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-245.yaml"},{"url":"https://groups.google.com/g/django-announce/c/8cz--gvaJr4"},{"url":"https://www.djangoproject.com/weblog/2022/aug/03/security-releases/"},{"url":"http://www.openwall.com/lists/oss-security/2022/08/03/1"},{"url":"https://security.netapp.com/advisory/ntap-20220915-0008/"},{"url":"https://github.com/advisories/GHSA-8x94-hmjh-97hq"},{"url":"https://www.debian.org/security/2022/dsa-5254"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI/"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:57Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qrw5-5h28-6cmg"},{"type":"CVE","value":"CVE-2022-41323"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-41323"},{"url":"https://github.com/django/django/commit/5b6b257fa7ec37ff27965358800c67e2dd11c924"},{"url":"https://www.djangoproject.com/weblog/2022/oct/04/security-releases/"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-304.yaml"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://security.netapp.com/advisory/ntap-20221124-0001/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FKYVMMR7RPM6AHJ2SBVM2LO6D3NGFY7B/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VZS4G6NSZWPTVXMMZHJOJVQEPL3QTO77/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YJB6FUBBLVKKG655UMTLQNN6UQ6EDLSP/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI/"},{"url":"https://github.com/advisories/GHSA-qrw5-5h28-6cmg"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:57Z","securityVulnerability":{"severity":"HIGH","package":{"name":"py"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w596-4wvx-j9j6"},{"type":"CVE","value":"CVE-2022-42969"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-42969"},{"url":"https://github.com/pytest-dev/py/issues/287"},{"url":"https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316"},{"url":"https://github.com/pytest-dev/py/issues/288"},{"url":"https://github.com/pytest-dev/pytest/issues/10392"},{"url":"https://news.ycombinator.com/item?id=34163710"},{"url":"https://pypi.org/project/py"},{"url":"https://github.com/advisories/GHSA-w596-4wvx-j9j6"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:57Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"certifi"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-43fp-rhv2-5gv8"},{"type":"CVE","value":"CVE-2022-23491"}],"references":[{"url":"https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8"},{"url":"https://github.com/certifi/python-certifi/commit/9e9e840925d7b8e76c76fdac1fab7e6e88c1c3b8"},{"url":"https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-23491"},{"url":"https://github.com/advisories/GHSA-43fp-rhv2-5gv8"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:57Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-q2jf-h9jm-m7p4"},{"type":"CVE","value":"CVE-2023-23969"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-23969"},{"url":"https://docs.djangoproject.com/en/4.1/releases/security/"},{"url":"https://www.djangoproject.com/weblog/2023/feb/01/security-releases/"},{"url":"https://lists.debian.org/debian-lts-announce/2023/02/msg00000.html"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://security.netapp.com/advisory/ntap-20230302-0007/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI/"},{"url":"https://github.com/advisories/GHSA-q2jf-h9jm-m7p4"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:58Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"IPython"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-29gw-9793-fvw7"},{"type":"CVE","value":"CVE-2023-24816"}],"references":[{"url":"https://github.com/ipython/ipython/security/advisories/GHSA-29gw-9793-fvw7"},{"url":"https://github.com/ipython/ipython/commit/385d69325319a5972ee9b5983638e3617f21cb1f"},{"url":"https://github.com/ipython/ipython/commit/991849c247fc208628879e7ca2923b3c218a5a75"},{"url":"https://github.com/Carreau/ipython/blob/7557ade0ed927475d5ab5b573d0ea4febfb22683/docs/source/whatsnew/version8.rst#ipython-810"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-24816"},{"url":"https://github.com/ipython/ipython/blob/3f0bf05f072a91b2a3042d23ce250e5e906183fd/IPython/utils/terminal.py#L103-L117"},{"url":"https://github.com/ipython/ipython/blob/56e6925dfa50e2c7f4a6471547b8176275db7c25/IPython/utils/_process_win32.py#L20"},{"url":"https://github.com/advisories/GHSA-29gw-9793-fvw7"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:58Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-2hrw-hx67-34x6"},{"type":"CVE","value":"CVE-2023-24580"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-24580"},{"url":"https://docs.djangoproject.com/en/4.1/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2023/feb/14/security-releases/"},{"url":"http://www.openwall.com/lists/oss-security/2023/02/14/1"},{"url":"https://github.com/django/django/commit/628b33a854a9c68ec8a0c51f382f304a0044ec92"},{"url":"https://github.com/django/django/commit/83f1ea83e4553e211c1c5a0dfc197b66d4e50432"},{"url":"https://github.com/django/django/commit/a665ed5179f5bbd3db95ce67286d0192eff041d8"},{"url":"https://lists.debian.org/debian-lts-announce/2023/02/msg00023.html"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FKYVMMR7RPM6AHJ2SBVM2LO6D3NGFY7B/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VZS4G6NSZWPTVXMMZHJOJVQEPL3QTO77/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YJB6FUBBLVKKG655UMTLQNN6UQ6EDLSP/"},{"url":"https://security.netapp.com/advisory/ntap-20230316-0006/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI/"},{"url":"https://github.com/advisories/GHSA-2hrw-hx67-34x6"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:58Z","securityVulnerability":{"severity":"HIGH","package":{"name":"sentry-sdk"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-29pr-6jr8-q5jm"},{"type":"CVE","value":"CVE-2023-28117"}],"references":[{"url":"https://github.com/getsentry/sentry-python/security/advisories/GHSA-29pr-6jr8-q5jm"},{"url":"https://github.com/getsentry/sentry-python/pull/1842"},{"url":"https://github.com/getsentry/sentry-python/releases/tag/1.14.0"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-28117"},{"url":"https://github.com/advisories/GHSA-29pr-6jr8-q5jm"}]}}}]},"grade":"E"}]}