{"totalCount":5,"grade":"D","repositories":[{"url":"https://github.com/MTES-MCT/sparte","vulnerabilityAlerts":{"totalCount":5,"nodes":[{"dismissedAt":null,"createdAt":"2022-09-22T14:10:24Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django-celery-results"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-fvx8-v524-8579"},{"type":"CVE","value":"CVE-2020-17495"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2020-17495"},{"url":"https://github.com/celery/django-celery-results/issues/142"},{"url":"https://github.com/celery/django-celery-results/issues/154"},{"url":"https://github.com/celery/django-celery-results/pull/316"},{"url":"https://github.com/advisories/GHSA-fvx8-v524-8579"}]}}},{"dismissedAt":null,"createdAt":"2022-10-18T21:28:30Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"py"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w596-4wvx-j9j6"},{"type":"CVE","value":"CVE-2022-42969"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-42969"},{"url":"https://github.com/pytest-dev/py/issues/287"},{"url":"https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316"},{"url":"https://github.com/pytest-dev/py/issues/288"},{"url":"https://github.com/pytest-dev/pytest/issues/10392"},{"url":"https://news.ycombinator.com/item?id=34163710"},{"url":"https://pypi.org/project/py"},{"url":"https://github.com/advisories/GHSA-w596-4wvx-j9j6"}]}}},{"dismissedAt":null,"createdAt":"2022-12-09T09:11:01Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"certifi"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-43fp-rhv2-5gv8"},{"type":"CVE","value":"CVE-2022-23491"}],"references":[{"url":"https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8"},{"url":"https://github.com/certifi/python-certifi/commit/9e9e840925d7b8e76c76fdac1fab7e6e88c1c3b8"},{"url":"https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-23491"},{"url":"https://github.com/advisories/GHSA-43fp-rhv2-5gv8"}]}}},{"dismissedAt":null,"createdAt":"2022-12-15T16:16:44Z","securityVulnerability":{"severity":"HIGH","package":{"name":"GitPython"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-hcpj-qp55-gfph"},{"type":"CVE","value":"CVE-2022-24439"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-24439"},{"url":"https://security.snyk.io/vuln/SNYK-PYTHON-GITPYTHON-3113858"},{"url":"https://github.com/gitpython-developers/GitPython/blob/bec61576ae75803bc4e60d8de7a629c194313d1c/git/repo/base.py#L1249"},{"url":"https://github.com/gitpython-developers/GitPython/issues/1515"},{"url":"https://github.com/gitpython-developers/GitPython/blob/bec61576ae75803bc4e60d8de7a629c194313d1c/git/repo/base.py%23L1249"},{"url":"https://github.com/gitpython-developers/GitPython/releases/tag/3.1.30"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IKMVYKLWX62UEYKAN64RUZMOIAMZM5JN/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SJHN3QUXPJIMM6SULIR3PR34UFWRAE7X/"},{"url":"https://github.com/advisories/GHSA-hcpj-qp55-gfph"}]}}},{"dismissedAt":null,"createdAt":"2023-02-03T22:23:46Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-q2jf-h9jm-m7p4"},{"type":"CVE","value":"CVE-2023-23969"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-23969"},{"url":"https://docs.djangoproject.com/en/4.1/releases/security/"},{"url":"https://www.djangoproject.com/weblog/2023/feb/01/security-releases/"},{"url":"https://lists.debian.org/debian-lts-announce/2023/02/msg00000.html"},{"url":"https://github.com/advisories/GHSA-q2jf-h9jm-m7p4"}]}}}]},"grade":"D"}]}