{"totalCount":5,"grade":"E","repositories":[{"url":"https://github.com/MTES-MCT/sparte","vulnerabilityAlerts":{"totalCount":5,"nodes":[{"dismissedAt":null,"createdAt":"2022-09-22T14:10:24Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django-celery-results"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-fvx8-v524-8579"},{"type":"CVE","value":"CVE-2020-17495"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2020-17495"},{"url":"https://github.com/celery/django-celery-results/issues/142"},{"url":"https://github.com/celery/django-celery-results/issues/154"},{"url":"https://github.com/celery/django-celery-results/pull/316"},{"url":"https://github.com/advisories/GHSA-fvx8-v524-8579"}]}}},{"dismissedAt":null,"createdAt":"2022-09-30T07:22:25Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"joblib"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-6hrg-qmvc-2xh8"},{"type":"CVE","value":"CVE-2022-21797"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-21797"},{"url":"https://github.com/joblib/joblib/issues/1128"},{"url":"https://github.com/joblib/joblib/pull/1321"},{"url":"https://github.com/joblib/joblib/commit/b90f10efeb670a2cc877fb88ebb3f2019189e059"},{"url":"https://security.snyk.io/vuln/SNYK-PYTHON-JOBLIB-3027033"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BVOMMW37OXZWU2EV5ONAAS462IQEHZOF/"},{"url":"https://github.com/advisories/GHSA-6hrg-qmvc-2xh8"}]}}},{"dismissedAt":null,"createdAt":"2022-10-18T18:42:04Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qrw5-5h28-6cmg"},{"type":"CVE","value":"CVE-2022-41323"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-41323"},{"url":"https://github.com/django/django/commit/5b6b257fa7ec37ff27965358800c67e2dd11c924"},{"url":"https://www.djangoproject.com/weblog/2022/oct/04/security-releases/"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-304.yaml"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://github.com/advisories/GHSA-qrw5-5h28-6cmg"}]}}},{"dismissedAt":null,"createdAt":"2022-10-18T21:28:30Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"py"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w596-4wvx-j9j6"},{"type":"CVE","value":"CVE-2022-42969"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-42969"},{"url":"https://github.com/pytest-dev/py/issues/287"},{"url":"https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316"},{"url":"https://github.com/pytest-dev/py/issues/288"},{"url":"https://github.com/pytest-dev/pytest/issues/10392"},{"url":"https://github.com/advisories/GHSA-w596-4wvx-j9j6"}]}}},{"dismissedAt":null,"createdAt":"2022-10-27T02:00:32Z","securityVulnerability":{"severity":"HIGH","package":{"name":"jupyter-core"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-m678-f26j-3hrp"},{"type":"CVE","value":"CVE-2022-39286"}],"references":[{"url":"https://github.com/jupyter/jupyter_core/security/advisories/GHSA-m678-f26j-3hrp"},{"url":"https://github.com/advisories/GHSA-m678-f26j-3hrp"}]}}}]},"grade":"E"}]}